### ISSUE TITLE
Make Web App Responsive for Different Screen Sizes

### ISSUE THREAD

**Issue by Devesh1509** [Devesh1509/advice-react-app#1]
Description: Ensure the web app adapts well to various screen sizes (e.g., mobile, tablet, desktop). Current design issues need to be resolved.

Acceptance Criteria:

1. Full responsiveness on mobile, tablet, and desktop.
2. Navigation adapts to smaller screens.

**Comment by Samaresh-Das** [comment]
I am willing to work on this. @Devesh1509

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue.
