### ISSUE TITLE
Enhance User Interface

### ISSUE THREAD

**Issue by Devesh1509** [Devesh1509/advice-react-app#2]
Description:
   Improve the user interface (UI) for better user experience.
   Improve the button's design for better aesthetics and UI/UX.

**Comment by Harrshhpattell** [comment]
Hi Devesh, I'm eager to enhance button designs for a more appealing user interface.

**Comment by Devesh1509** [comment]
@Harrshhpattell sure ,you can start working on it.

**Comment by Harrshhpattell** [comment]
Assign me 🥲

**Comment by Harrshhpattell** [comment]
The project currently utilizes a React class component, which presents an opportunity for enhancement by transitioning it into a functional component. Class components are considered older and less concise when compared to their functional counterparts.

I am suggesting the conversion of the existing React class component into a functional one. This transformation aims to optimize the codebase, enhance readability, and leverage modern React features like hooks.

Could you kindly confirm whether I have permission to proceed with this conversion, or if you prefer that I focus solely on customizing the CSS?

**Comment by Harrshhpattell** [comment]
can u reply me plzz so i can start work on it

**Comment by Devesh1509** [comment]
> can u reply me plzz so i can start work on it

go ahead , you can start working on it
